name: E2E matrix

on:
  push:
    branches:
      - test
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:
    inputs:
      debug_enabled:
        description: 'Run the build with tmate debugging enabled (https://github.com/marketplace/actions/debugging-with-tmate)'
        required: false
        default: false

jobs:
  install:
    strategy:
        matrix:
          os:
            - ubuntu-latest
#             - macos-latest
          include:
            - os: ubuntu-latest
              os-name: ubuntu
              os-cache-dir: /tmp/nx-cache
#             - os: macos-latest
#               os-name: osx
#               os-cache-dir: /tmp/nx-cache
          node_version:
            - '16'
#             - '18'
        fail-fast: false
    name: ${{ matrix.os-name }}/${{ matrix.node_version }} - ${{ matrix.package_manager }} - ${{ matrix.packages }}
    runs-on: ${{ matrix.os }}
    outputs:
      os:  ${{ matrix.os}}
    steps:
      - id: notify_os
        run: |
          echo "::set-output name=value::$(echo ${{ matrix.os }} )"

#       - name: Checkout
#         uses: actions/checkout@v2
#         with:
#           fetch-depth: 1

#       - name: Install PNPM
#         if: ${{ matrix.package_manager == 'pnpm' }}
#         uses: pnpm/action-setup@v2.2.1
#         with:
#           version: 7.1.0

#       - name: Use Node.js ${{ matrix.node_version }}
#         uses: actions/setup-node@v2.4.0
#         with:
#           node-version: ${{ matrix.node_version }}

#       - name: Yarn cache directory path
#         id: yarn-cache-dir-path
#         run: echo "::set-output name=dir::$(yarn cache dir)"

#       - name: Cache yarn
#         uses: actions/cache@v2
#         with:
#           path: ${{ steps.yarn-cache-dir-path.outputs.dir }}
#           key: ${{ matrix.os }}-node-${{ matrix.node_version }}-yarn-${{ hashFiles('yarn.lock') }}
#           restore-keys: |
#             ${{ matrix.os }}-node-${{ matrix.node_version }}-yarn-

#       - name: Install packages
#         run: yarn install --prefer-offline --frozen-lockfile --non-interactive

#       - name: Install applesimutils, reset ios simulators
#         if: ${{ matrix.os == 'macos-latest' }}
#         run: |
#           HOMEBREW_NO_AUTO_UPDATE=1 brew tap wix/brew >/dev/null
#           HOMEBREW_NO_AUTO_UPDATE=1 brew install applesimutils >/dev/null
#           xcrun simctl shutdown all && xcrun simctl erase all


  e2e:
    needs: install
    runs-on: ${{ needs.install.outputs.os }}
    strategy:
      matrix:
        packages:
          - e2e-angular-core
          - e2e-angular-extensions
          - e2e-nx-run,e2e-nx-misc,e2e-nx-plugin
          - e2e-jest
          - e2e-linter
          - e2e-cypress
          - e2e-react
          - e2e-next
          - e2e-node
          - e2e-web
          - e2e-storybook,e2e-storybook-angular
          - e2e-workspace-create
          - e2e-react-native
          # - e2e-detox
          - e2e-add-nx-to-monorepo
          - e2e-dep-graph-client
      fail-fast: false

    name:  ${{ matrix.packages }}
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 1

      - name: Run e2e tests
        run: yarn nx run-many --target=e2e --projects="${{ join(matrix.packages) }}" --parallel=1
        env:
          GIT_AUTHOR_EMAIL: test@test.com
          GIT_AUTHOR_NAME: Test
          GIT_COMMITTER_EMAIL: test@test.com
          GIT_COMMITTER_NAME: Test
          NX_E2E_CI_CACHE_KEY: e2e-gha-${{ matrix.os }}-${{ matrix.node_version }}-${{ matrix.package_manager }}
          NX_E2E_RUN_CYPRESS: ${{ 'true' }}
          NODE_OPTIONS: --max_old_space_size=8192
          SELECTED_PM: ${{ matrix.package_manager }}
          npm_config_registry: http://localhost:4872
          YARN_REGISTRY: http://localhost:4872
          NX_VERBOSE_LOGGING: ${{ 'true' }}
          NX_E2E_SKIP_BUILD_CLEANUP: ${{ 'true' }}
          NX_CACHE_DIRECTORY: ${{ matrix.os-cache-dir }}

      - name: Setup tmate session
        if: ${{ github.event_name == 'workflow_dispatch' && github.event.inputs.debug_enabled && failure() }}
        uses: mxschmitt/action-tmate@v3.8
